USE sakila;
-- challenge 1:List the number of films per category.

SELECT 
    c.name AS category,
    COUNT(fc.film_id) AS film_count
FROM category AS c
JOIN film_category AS fc
    ON c.category_id = fc.category_id
GROUP BY c.category_id, c.name
ORDER BY film_count DESC;

-- challenge 2:Retrieve the store ID, city, and country for each store.
SELECT 
    s.store_id,
    ci.city,
    co.country
FROM store AS s
JOIN address AS a
    ON s.address_id = a.address_id
JOIN city AS ci
    ON a.city_id = ci.city_id
JOIN country AS co
    ON ci.country_id = co.country_id;

-- challenge 3:Calculate the total revenue generated by each store in dollars.
SELECT 
    s.store_id,
    SUM(p.amount) AS total_revenue
FROM payment AS p
JOIN staff AS st
    ON p.staff_id = st.staff_id
JOIN store AS s
    ON st.store_id = s.store_id
GROUP BY s.store_id;

-- challenge 4:Determine the average running time of films for each category.

SELECT
    c.name AS category,
    AVG(f.length) AS avg_length_minutes
FROM category AS c
JOIN film_category AS fc
    ON c.category_id = fc.category_id
JOIN film AS f
    ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY c.name;